import mongoose from 'mongoose';
import { createRequire } from 'module';
import dotenv from 'dotenv';
const require = createRequire(import.meta.url);
import Service from './models/Service.js';

// Load environment variables
dotenv.config();

// Configuration
const MONGODB_URI = process.env.MONGODB_URI || process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/smart-homez';

// Auto-generated subscription plan IDs that should be removed
const DEFAULT_PLAN_IDS = ['oneTime', 'daily', 'bi-weekly', 'weekly', 'monthly'];

async function cleanupAutoGeneratedSubscriptionPlans() {
  try {
    // Connect to MongoDB
    await mongoose.connect(MONGODB_URI);
    console.log('📡 Connected to MongoDB');

    // Find all services with subscription plans
    const services = await Service.find({
      subscriptionPlans: { $exists: true, $ne: [] }
    });

    console.log(`🔍 Found ${services.length} services with subscription plans`);

    let cleanedCount = 0;
    let skippedCount = 0;

    for (const service of services) {
      // Check if all subscription plans are auto-generated defaults
      const hasOnlyDefaults = service.subscriptionPlans.every(plan =>
        DEFAULT_PLAN_IDS.includes(plan.id) &&
        plan.description && (
          plan.description.includes('Single service') ||
          plan.description.includes('6 days/week') ||
          plan.description.includes('2 days/week') ||
          plan.description.includes('1 day/week') ||
          plan.description.includes('Once a month')
        )
      );

      // Check if service has exactly the 5 default plans (typical auto-generated set)
      const hasAllDefaults = service.subscriptionPlans.length === 5 &&
        DEFAULT_PLAN_IDS.every(id => service.subscriptionPlans.some(plan => plan.id === id));

      // Remove default plans if they appear to be auto-generated
      if (hasOnlyDefaults || hasAllDefaults) {
        console.log(`🧹 Cleaning service: ${service.name} (${service._id})`);

        // Clear subscription plans
        await Service.updateOne(
          { _id: service._id },
          { $set: { subscriptionPlans: [] } }
        );

        cleanedCount++;
      } else {
        console.log(`⏭️  Skipping service: ${service.name} (has custom plans)`);
        skippedCount++;
      }
    }

    console.log('\n✅ Cleanup completed!');
    console.log(`🧹 Cleaned: ${cleanedCount} services`);
    console.log(`⏭️  Skipped: ${skippedCount} services (had custom plans)`);
    console.log('\n📝 Result: Only admin-configured subscription plans will now be visible');

    // Close connection
    await mongoose.disconnect();
    console.log('📡 Disconnected from MongoDB');

  } catch (error) {
    console.error('❌ Cleanup failed:', error);
    process.exit(1);
  }
}

// Check if script is run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  cleanupAutoGeneratedSubscriptionPlans();
}

export default cleanupAutoGeneratedSubscriptionPlans;