import mongoose from 'mongoose';

const bookingSchema = new mongoose.Schema({
  customer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  worker: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: false // Made optional as worker will be assigned by algorithm
  },
  // Worker assignment details
  assignmentMethod: {
    type: String,
    enum: ['auto', 'manual', 'customer-preferred'],
    default: 'auto'
  },
  assignedAt: {
    type: Date,
    default: null
  },
  backupWorkers: [{
    worker: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    assignedAt: Date,
    priority: Number
  }],
  service: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Service',
    required: true
  },
  bookingDate: {
    type: Date,
    required: [true, 'Booking date is required']
  },
  startTime: {
    type: String,
    required: [true, 'Start time is required']
  },
  endTime: {
    type: String,
    required: [true, 'End time is required']
  },
  status: {
    type: String,
    enum: ['pending', 'confirmed', 'in-progress', 'completed', 'cancelled'],
    default: 'pending'
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0
  },
  // Recurring booking details
  bookingType: {
    type: String,
    enum: ['oneTime', 'daily', 'weekly', 'monthly'],
    default: 'oneTime'
  },
  isRecurring: {
    type: Boolean,
    default: false
  },
  recurringSchedule: {
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly']
    },
    startDate: Date,
    endDate: Date,
    nextScheduledDate: Date,
    completedOccurrences: {
      type: Number,
      default: 0
    },
    totalOccurrences: Number
  },
  parentBooking: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Booking',
    default: null // For recurring bookings, links to the original booking
  },
  // Customer preferences for this booking
  preferences: {
    workerGenderPreference: {
      type: String,
      enum: ['any', 'male', 'female'],
      default: 'any'
    },
    languagePreference: String,
    religionPreference: String,
    specialInstructions: {
      type: String,
      maxlength: 500
    }
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'qr-generated', 'worker-confirmed', 'paid', 'refunded', 'failed'],
    default: 'pending'
  },
  paymentMethod: {
    type: String,
    enum: ['qr-upi', 'cash', 'card', 'other'],
    default: 'qr-upi'
  },
  qrPayment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'QRPayment',
    default: null
  },
  location: {
    address: String,
    city: String,
    state: String,
    zipCode: String
  },
  notes: {
    type: String,
    default: ''
  },
  cancellationReason: {
    type: String,
    default: null
  },
  rating: {
    type: Number,
    min: 0,
    max: 5,
    default: null
  },
  review: {
    type: String,
    default: null
  },
  // Service Start/End QR Code Tracking
  serviceStartQRCode: {
    type: String,
    default: null // Generated by worker when ready to start
  },
  serviceEndQRCode: {
    type: String,
    default: null // Generated by worker when ready to end
  },
  actualStartTime: {
    type: Date,
    default: null // Set when customer scans start QR
  },
  actualEndTime: {
    type: Date,
    default: null // Set when customer scans end QR
  },
  termsAccepted: {
    type: Boolean,
    default: false // Customer accepts terms before service start
  },
  termsAcceptedAt: {
    type: Date,
    default: null
  },
  jobDescriptionAcknowledged: {
    type: Boolean,
    default: false // Worker acknowledges job description
  },
  jobDescriptionAcknowledgedAt: {
    type: Date,
    default: null
  },
  actualDurationMinutes: {
    type: Number,
    default: null // Calculated from actualStartTime and actualEndTime
  },
  scheduledDurationMinutes: {
    type: Number,
    default: null // Calculated from startTime and endTime
  },
  overtimeMinutes: {
    type: Number,
    default: 0 // Calculated if actualDuration > scheduledDuration
  },
  overtimeCharges: {
    type: Number,
    default: 0 // Additional charges for overtime
  },
  // Work Documentation (REQ-C-012)
  workDocumentation: {
    photos: [{
      url: {
        type: String,
        required: true
      },
      type: {
        type: String,
        enum: ['before', 'during', 'after'],
        required: true
      },
      timestamp: {
        type: Date,
        default: Date.now
      },
      notes: {
        type: String,
        default: ''
      },
      uploadedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
      }
    }],
    additionalNotes: {
      type: String,
      default: ''
    }
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Index for faster queries
bookingSchema.index({ customer: 1, bookingDate: -1 });
bookingSchema.index({ worker: 1, bookingDate: -1 });
bookingSchema.index({ status: 1 });

const Booking = mongoose.model('Booking', bookingSchema);

export default Booking;
